config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' 
  }
  resources :shots do 
  	resources :comments 
  	member do 
  		put 'like', to: "shots#like"
  		put 'unlike', to: "shots#unlike"
  	end
  end
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
 
 
 
  root 'shots#index'
  
  get 'maps/index', to: 'maps#index'
  resources :maps, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
    resources :users do
    member do
      get :following, :followers
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HIDDENGEM</title>
    <%= csrf_meta_tags %>
 		<meta name="viewport" content="width=device-width, initial-scale=1">
 		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://use.fontawesome.com/releases/v5.6.3/css/all.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Lexend+Tera&display=swap" rel="stylesheet">
    <%= favicon_link_tag asset_path("favicon.ico") %>
  </head>
  <body>
  	<% if flash[:notice] %>
    	<div class="notification is-primary global-notification">
  	  	<p class="notice"><%= notice %></p>
    	</div>
   	<% end %>
    <% if flash[:alert] %>
    <div class="notification is-primary global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5 has-text-white">H I D D E N G E M</h1>
        <% end  %>
      <div id="navbar" class="navbar-menu">
            </div>
          </div>
        </div>
      </div>
    </nav> 
 <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              
              <% if user_signed_in? %>

              <p class="control">
                <%= link_to new_shot_path, class:"button is-white" do %>
              <i class="fas fa-cloud-upload-alt">UPLOAD</i>                
              <% end %>
              </p>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class:"button is-white fas fa-user-cog" %>
              </p>
              <p class="control">
               <%= link_to destroy_user_session_path, method: :delete, class:"button is-white" do %>
                <i class="fas fa-sign-out-alt">Log Out</i>
                <% end %>
               </p>
              <% else %>
              <p class="control">
                <%= link_to new_user_session_path, class:"button is-white" do %>
                <i class="fas fa-sign-out-alt">Sign In</i>
                <% end %>
              </p>
               <p class="control">
                <%= link_to new_user_registration_path, class:"button is-white" do %>
                <i class="fas fa-user-plus"> Sign Up</i>
                <% end %>
              </p>
              <% end %>
            </div>
          </div>
        </div>
    <%= yield %>
    <footer>(c) HIDDENGEM KEIJI OKITA PORTFOLIO 2020</footer>
  </body>
</html>